{
    "title": "A flaw was found in privoxy before 3.0.32. A invalid read of size two may occur in chunked_body_is_complete() leading to denial of service.",
    "score": 7.5,
    "severity": "HIGH",
    "cwe_id": "CWE-125",
    "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
    "cpe_match": [
        "cpe:2.3:a:privoxy:privoxy:*:*:*:*:*:*:*:*",
        "cpe:2.3:o:debian:debian_linux:9.0:*:*:*:*:*:*:*"
    ],
    "cve_source": [
        "NVD"
    ],
    "ttpMapping": [
        {
            "techniqueId": "T1543",
            "confidence": "14.7",
            "techniqueName": "Create or Modify System Process"
        }
    ]
}
