{
    "title": "validators.URLValidator in Django 1.8.x before 1.8.3 allows remote attackers to cause a denial of service (CPU consumption) via unspecified vectors.",
    "score": 7.8,
    "severity": "HIGH",
    "cwe_id": "CWE-399",
    "cvss_vector": "CVSS:2.0/AV:N/AC:L/Au:N/C:N/I:N/A:C",
    "cpe_match": [
        "cpe:2.3:a:djangoproject:django:1.8.2:*:*:*:*:*:*:*",
        "cpe:2.3:a:djangoproject:django:1.8.1:*:*:*:*:*:*:*",
        "cpe:2.3:a:djangoproject:django:1.8.0:*:*:*:*:*:*:*"
    ],
    "cve_source": [
        "NVD"
    ],
    "ttpMapping": [
        {
            "techniqueId": "T1498",
            "techniqueName": "Network Denial of Service",
            "confidence": "43.6"
        },
        {
            "techniqueId": "T1499",
            "techniqueName": "Endpoint Denial of Service",
            "confidence": "47.3"
        },
        {
            "techniqueId": "T1548",
            "techniqueName": "Abuse Elevation Control Mechanism",
            "confidence": "3.6"
        },
        {
            "techniqueId": "T1574",
            "techniqueName": "Hijack Execution Flow",
            "confidence": "2.4"
        }
    ]
}
