{
    "title": "An issue was discovered in Django 2.2 before 2.2.26, 3.2 before 3.2.11, and 4.0 before 4.0.1. UserAttributeSimilarityValidator incurred significant overhead in evaluating a submitted password that was artificially large in relation to the comparison values. In a situation where access to user registration was unrestricted, this provided a potential vector for a denial-of-service attack.",
    "score": 7.5,
    "severity": "HIGH",
    "cwe_id": "NVD-CWE-Other",
    "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
    "cpe_match": [
        "cpe:2.3:a:djangoproject:django:*:*:*:*:*:*:*:*",
        "cpe:2.3:a:djangoproject:django:*:*:*:*:*:*:*:*",
        "cpe:2.3:a:djangoproject:django:*:*:*:*:*:*:*:*",
        "cpe:2.3:o:fedoraproject:fedora:35:*:*:*:*:*:*:*"
    ],
    "cve_source": [
        "NVD"
    ],
    "ttpMapping": []
}
